

module AbsCpp where

-- Haskell module generated by the BNF converter




newtype Id = Id String deriving (Eq, Ord, Show, Read)
data Program = PDefs [Def]
  deriving (Eq, Ord, Show, Read)

data Def
    = DFun Type Id [Arg] [Stm]
    | DFunSBdy Type Id [Arg]
    | DFunInline Type Id [Arg] [Stm]
    | DFunSBdyIL Type Id [Arg]
    | DUs QConst
    | DType Type Id
    | DDecls Decl
    | DStruct Id [Decl]
  deriving (Eq, Ord, Show, Read)

data Decl = Decl Type [Id] | DInit Type Id Exp
  deriving (Eq, Ord, Show, Read)

data Arg
    = ADeclBlnck Type
    | ADecl Type Id
    | ADeclIn Type Id Exp
    | AConst Arg
    | ATodos Arg
  deriving (Eq, Ord, Show, Read)

data Stm
    = SEmpty
    | SExp Exp
    | SDecls Decl
    | SReturn Exp
    | SReturnVoid
    | SWhile Exp Stm
    | SDoWhile Stm Exp Stm
    | SBlock [Stm]
    | SIf Exp Stm
    | SIfElse Exp Stm Stm
    | SFor Decl Exp Exp Stm
    | SType Type Id
    | SConst Type Exp
    | SStruct Id [Decl]
  deriving (Eq, Ord, Show, Read)

data QId = QId Id | QIdT Id [Type]
  deriving (Eq, Ord, Show, Read)

data QConst = QConst [QId]
  deriving (Eq, Ord, Show, Read)

data Exp
    = ETrue
    | EFalse
    | EInt Integer
    | EDouble Double
    | EChar Char
    | EString [String]
    | EQct QConst
    | EArr Id Exp
    | EApp Id [Exp]
    | EPEstr Exp Exp
    | EProy Exp Exp
    | EPIncr Exp
    | EPDecr Exp
    | EIncr Exp
    | EDecr Exp
    | ENeg Exp
    | ETimes Exp Exp
    | EDiv Exp Exp
    | ERest Exp Exp
    | EPlus Exp Exp
    | EMinus Exp Exp
    | EShiftL Exp Exp
    | EShiftR Exp Exp
    | ELt Exp Exp
    | EGt Exp Exp
    | ELtEq Exp Exp
    | EGtEq Exp Exp
    | EEq Exp Exp
    | ENEq Exp Exp
    | EAnd Exp Exp
    | EOr Exp Exp
    | EMinAss Exp Exp
    | EAddAss Exp Exp
    | EAss Exp Exp
    | ECond Exp Exp Exp
    | EExcp Exp
    | ETyped Exp Type
  deriving (Eq, Ord, Show, Read)

data BuilInType
    = BuilInType_bool
    | BuilInType_int
    | BuilInType_double
    | BuilInType_void
  deriving (Eq, Ord, Show, Read)

data Type = TypeB BuilInType | TypeQ QConst | TypeP Type
  deriving (Eq, Ord, Show, Read)

